<?php

$lang = array(
	'xbdt_bulk_dev_tools'                => 'Bulk Dev Tools',
	'xbdt_action'                        => 'Action',
	'xbdt_action_build'                  => 'Build Application (XML, lang, themes, hooks, etc.)',
	'xbdt_action_compilejs'              => 'Compile JavaScript only',
	'xbdt_action_download'               => 'Rebuild & Download (.tar)',
	'xbdt_download_mode'                 => 'Download Mode',
	'xbdt_download_zip'                  => 'All in one ZIP bundle',
	'xbdt_download_individual'           => 'Individual .tar files',
	'xbdt_apps'                          => 'Applications',
	'xbdt_apps_desc'                     => 'Custom apps are pre-selected. Core/protected apps are unchecked by default.',
	'xbdt_process_complete'              => 'All selected applications processed successfully.',
	'xbdt_building'                      => 'Building: %s (%s/%s)',
	'xbdt_compiling_js'                  => 'Compiling JS: %s (%s/%s)',
	'xbdt_download_results'              => 'Download Ready',
	'xbdt_download_results_desc'         => 'All selected applications have been rebuilt. Choose your download method:',
	'xbdt_download_all_zip'              => 'Download All as ZIP',
	'xbdt_download_tar'                  => 'Download .tar',
	'xbdt_errors_occurred'               => 'Some items had errors during processing:',
	'xbdt_no_apps_selected'              => 'No applications were selected.',
	'xbdt_bulk_download_plugins'         => 'Bulk Download Plugins',
	'xbdt_plugin_download_mode'          => 'Download Mode',
	'xbdt_plugin_download_zip'           => 'All in one ZIP bundle',
	'xbdt_plugin_download_individual'    => 'Individual .xml files',
	'xbdt_plugins'                       => 'Plugins',
	'xbdt_no_plugins_selected'           => 'No plugins were selected.',
	'xbdt_exporting_plugin'              => 'Exporting: %s (%s/%s)',
	'xbdt_plugin_download_results'       => 'Plugin Downloads Ready',
	'xbdt_plugin_download_results_desc'  => 'All selected plugins have been exported. Choose your download method:',
	'xbdt_plugin_download_all_zip'       => 'Download All as ZIP',
	'xbdt_plugin_download_xml'           => 'Download .xml',
);
