<?php

$lang = array(
	'xbdt_bulk_dev_tools'                => 'Bulk Dev Tools',
	'xbdt_action'                        => 'Action',
	'xbdt_action_build'                  => 'Build Application (XML, lang, themes, hooks, etc.)',
	'xbdt_action_compilejs'              => 'Compile JavaScript only',
	'xbdt_action_download'               => 'Rebuild & Download (.tar)',
	'xbdt_download_mode'                 => 'Download Mode',
	'xbdt_download_zip'                  => 'All in one ZIP bundle',
	'xbdt_download_individual'           => 'Individual .tar files',
	'xbdt_apps'                          => 'Applications',
	'xbdt_apps_desc'                     => 'Custom apps are pre-selected. Core/protected apps are unchecked by default.',
	'xbdt_process_complete'              => 'All selected applications processed successfully.',
	'xbdt_building'                      => 'Building: %s (%s/%s)',
	'xbdt_compiling_js'                  => 'Compiling JS: %s (%s/%s)',
	'xbdt_download_results'              => 'Download Ready',
	'xbdt_download_results_desc'         => 'All selected applications have been rebuilt. Choose your download method:',
	'xbdt_download_all_zip'              => 'Download All as ZIP',
	'xbdt_download_tar'                  => 'Download .tar',
	'xbdt_errors_occurred'               => 'Some items had errors during processing:',
	'xbdt_no_apps_selected'              => 'No applications were selected.',
	'xbdt_bulk_download_plugins'         => 'Bulk Download Plugins',
	'xbdt_plugin_download_mode'          => 'Download Mode',
	'xbdt_plugin_download_zip'           => 'All in one ZIP bundle',
	'xbdt_plugin_download_individual'    => 'Individual .xml files',
	'xbdt_plugins'                       => 'Plugins',
	'xbdt_no_plugins_selected'           => 'No plugins were selected.',
	'xbdt_exporting_plugin'              => 'Exporting: %s (%s/%s)',
	'xbdt_plugin_download_results'       => 'Plugin Downloads Ready',
	'xbdt_plugin_download_results_desc'  => 'All selected plugins have been exported. Choose your download method:',
	'xbdt_plugin_download_all_zip'       => 'Download All as ZIP',
	'xbdt_plugin_download_xml'           => 'Download .xml',

	/* Sync Plugin Versions */
	'xbdt_sync_plugin_versions'          => 'Sync Plugin Versions',
	'xbdt_sync_mismatch_warning'         => 'Some plugins have versions in dev/versions.json that do not match the database. Click "Fix All" to update the database to match.',
	'xbdt_sync_all_ok'                   => 'All plugin versions are in sync between dev/versions.json and the database.',
	'xbdt_sync_fix_all'                  => 'Fix All Out-of-Sync',
	'xbdt_sync_col_plugin'              => 'Plugin',
	'xbdt_sync_col_db_version'          => 'DB Version',
	'xbdt_sync_col_dev_version'         => 'Dev Version',
	'xbdt_sync_col_status'              => 'Status',
	'xbdt_sync_no_versions_file'        => 'No versions.json',
	'xbdt_sync_status_unknown'          => 'Unknown',
	'xbdt_sync_status_ok'               => 'In Sync',
	'xbdt_sync_status_mismatch'         => 'Out of Sync',
	'xbdt_sync_fixed'                   => 'Updated %s plugin(s) to match dev/versions.json.',
);
